// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  throw new Error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY — set build-time envs.');
}

// --- runtime diag (temporary) ---
if (import.meta.env.PROD) {
  try {
    const urlHost = new URL(SUPABASE_URL!).host; // e.g., dycjwrgieaontfzkfqvw.supabase.co
    const anon = SUPABASE_KEY!;
    const payloadB64 = anon.split('.')[1];
    const payloadJson = JSON.parse(atob(payloadB64));
    const issHost = new URL(payloadJson.iss || 'https://invalid').host; // e.g., abcdef.supabase.co
    const match = urlHost.startsWith(issHost.split('.')[0]); // compare refs
    // eslint-disable-next-line no-console
   console.log('[JWT_MATCH]', { urlHost, issHost, match });
  } catch (e) {
    // eslint-disable-next-line no-console
    console.log('[JWT_MATCH_ERR]', String(e));
  }
}
// --- end diag ---

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
export const __SUPA = { SUPABASE_URL, SUPABASE_KEY_DEFINED: !!SUPABASE_KEY };